import '../styles/globals.css';
import Head from 'next/head';

import Header from '../components/Header';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Ariana Daris | Fullstack Developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="w-full">
        <Header />
        <main>
          <Component {...pageProps} />
        </main>
      </div>

    </>

  )
}

export default MyApp
